var g_aliases = 
[
	"bag sack",
	"bandaid band-aid",
	"beg beggar",
	"blade sharp pointy stick weapon spike",
	"bomb boom explosive tnt pow",
	"boob tit breast",
	"bottle jar container bowl",
	"box rectangle square cube",
	"break destroy broken",
	"charge recharge re-charge battery",
	"circle ball round sphere disk disc",
	"consumable singleuse single-use",
	"cord rope string",
	"cross + religious religion sacrifice blaspheme blasphemy sacreligious",
	"dark black",
	"dead corpse death body",
	"dice reroll re-roll geek nerd",
	"drip tear drop teardrop wet liquid",
	"dupe duplicate",
	"face head",
	"familiar baby follow follower child kid",
	"fart gas",
	"food eat",
	"fire flame",
	"fly flies parasite",
	"gamble bet",
	"garbage trash",
	"glow shimmer",
	"ghost spirit",
	"grey gray silver",
	"gross puke yuck",
	"gold yellow",
	"guts entrails intestines",
	"hat cap",
	"heart <3",
	"hole opening orifice",
	"horoscope horroscope zodiac",
	"jewelry necklace locket charm",
	"knife cut",
	"large big huge",
	"larva bug grub maggot",
	"light white bright",
	"map floor",
	"metal steel",
	"mom bitch",
	"money cash coin dollar $",
	"needle syringe inject",
	"nintendo game mario",
	"paper page sheet",
	"pill capsule cylinder",
	"pink flesh",
	"photo picture",
	"poop shit crap turdy dookie pile",
	"satan devil demon evil",
	"screw nail",
	"shakey jittery",
	"shine shiny",
	"spooky scary creepy",
	"stone rock",
	"symbol shape glyph sign",
	"tech device",
	"testicles balls",
	"teeth tooth dental",
	"text writing",
	"one single 1",
	"two double 2",
	"three triple triangle 3",
	"four quad 4",
	"five 5",
	"six 6",
	"seven 7",
	"eight 8 infinity infinite",
	"nine 9",
	"ten 10"
];