var aliases = 
[
	"bandaid band-aid",
	"beg beggar",
	"blade sharp",
	"bomb boom explosive tnt",
	"break destroy",
	"charge recharge re-charge battery",
	"circle ball round sphere",
	"consumable singleuse single-use",
	"cord rope"
	"dark black",
	"dice reroll re-roll",
	"dupe duplicate",
	"face head",
	"familiar baby follow follower",
	"fart gas",
	"fire flame",
	"fly flies",
	"gamble bet",
	"grey gray silver",
	"hat cap",
	"heart <3",
	"horoscope horroscope zodiac",
	"knife cut",
	"large big huge",
	"larva bug maggot",
	"light white bright",
	"map floor",
	"money cash coin",
	"photo picture",
	"poop shit crap",
	"satan devil demon evil",
	"screw nail",
	"shine shiny",
	"symbol shape",
	"tear drop teardrop",
	"testicles balls",
	"text writing",
	"one 1",
	"two 2",
	"three 3",
	"four 4",
	"five 5",
	"six 6",
	"seven 7",
	"eight 8 infinity infinite",
	"nine 9",
	"ten 10"
];