var g_aliases = 
[
	"bag sack",
	"bandaid band-aid",
	"beg beggar",
	"blade sharp pointy stick weapon spike",
	"bomb boom explosive tnt",
	"bottle jar",
	"box rectangle square cube",
	"break destroy",
	"charge recharge re-charge battery",
	"circle ball round sphere disk disc",
	"consumable singleuse single-use",
	"cord rope string",
	"cross +",
	"dark black",
	"dead corpse",
	"dice reroll re-roll geek nerd",
	"dupe duplicate",
	"face head",
	"familiar baby follow follower",
	"fart gas",
	"fire flame",
	"fly flies",
	"gamble bet",
	"glow shimmer",
	"grey gray silver",
	"gold yellow",
	"hat cap",
	"heart <3",
	"horoscope horroscope zodiac",
	"jewelry necklace",
	"knife cut",
	"large big huge",
	"larva bug grub maggot",
	"light white bright",
	"map floor",
	"metal steel",
	"mom bitch",
	"money cash coin",
	"needle syringe inject",
	"nintendo game mario",
	"paper page sheet",
	"pill capsule cylinder",
	"pink flesh",
	"photo picture",
	"poop shit crap turdy dookie",
	"satan devil demon evil",
	"screw nail",
	"shakey jittery",
	"shine shiny",
	"stone rock",
	"symbol shape glyph",
	"tech device",
	"testicles balls",
	"text writing",
	"wet drip tear drop teardrop",
	"one single 1",
	"two double 2",
	"three triple triangle 3",
	"four quad 4",
	"five 5",
	"six 6",
	"seven 7",
	"eight 8 infinity infinite",
	"nine 9",
	"ten 10"
];