// Workflow:
//
// 1) open the isaac wiki page to scrape (i.e. http://bindingofisaacrebirth.gamepedia.com/Trinkets)
// 2) type listTables() to find the index of the table to be scraped
// 3) set g_layout to the correct layout.  Paste this file directly in the dev console
// 4) type copy(scrapeTable(i)) and copy(scrapeTableForTagging(i)) to scrape the ith table, paste the output of 
//    each in separate .json files
//
//      NOTE: they helpfully added a div named "copy" to the pages, you must locate and delete it to allow the copy() command to work
//
// 5) there may be more than one table of items to scrape per page, so run for several i's
// 6) wire the files up in index.html and prepareData() to pull them in at page load time
// 7) most images have been base64 encoded into spritesheet/base64thumbnails.json, that file is generated by imgURLencoder.js, see that file for details
//
// Why two files per scrape:  we want to be able to tag each item with our own descriptive search terms, but we also want
// to be able to re-scrape the items as they get updated, without nuking those tags.

var g_itemLayout = { descriptionCol: 4, iconCol: 2 };
var g_runeLayout = { descriptionCol: 5, iconCol: 2 };
var g_cardLayout = g_itemLayout;
var g_trinketLayout = g_itemLayout;

var g_layout = g_itemLayout;
function scrapeTable(tableIndex)
{
	return JSON.stringify(extractToJSON(getTable(tableIndex), rowImageAndThumbnailScrape), null, '\t');
}
function scrapeTableForTagging(tableIndex)
{
	return JSON.stringify(extractToJSON(getTable(tableIndex), rowMetadataTemplateScrape), null, '\t');
}
function extractToJSON(table, rowScraper)
{
	var retval = {};

	var nRows = table.rows.length;
	for (var r = 1; r < nRows; ++r)
	{
		var row = table.rows[r];
		var nCols = row.cells.length;

		var name = row.cells[0].textContent.trim();
		retval[name] = rowScraper(row);
	}
	return retval;
}
function rowImageAndThumbnailScrape(row)
{
	var entry = {};

	var anchor = getChildTag(row.cells[0], "a");
	if (anchor)
	{
		entry.wikiPage = anchor.href;
	}

	// cards/runes have the "DLC" icon before the item icon.
	var iconCol = row.cells[g_layout.iconCol];
	var img = getChildTag(iconCol, "img");
	entry.thumbnail = img.src.split('?version=')[0];

	var description = row.cells[g_layout.descriptionCol];
	entry.descriptionHTML = description.innerHTML.trim();
	return entry;
}
function rowMetadataTemplateScrape(row)
{
	var entry = {};
	entry.itemType = "";
	entry.itemColor = "";
	entry.itemTags = "";
	return entry;
}
function getTable(index)
{
	return document.body.getElementsByTagName("table")[index];
}
function listTables()
{
	const tables = document.body.getElementsByTagName("table");
	var i = 0;
	for (table of tables) {
		if (table.rows.length > 1) {
			const headers = table.tHead ? 
				[...table.tHead.rows[0].cells].map(cell => cell.textContent.trim()).join(',') :
				['--'];

			const firstCell = table.rows[1].cells[0].textContent;
			console.log(`table ${i}, headers: [${headers}], first item: ${firstCell}`);
		}
		else {
			console.log(`table ${i} empty`);
		}
		++i;
	}
}
function getChildTag(el, tagName, index)
{
	index = index || 0;

	var elements = el.getElementsByTagName(tagName);
	return elements && (elements.length > index) && elements[index];
}