// our tag thesaurus
var g_aliases = 
[
	"! ? question exclamation mark",
	"animal beast critter",
	"bag sack",
	"bandaid band-aid",
	"beg beggar",
	"blood bloody bleed bleeding",
	"blade sharp pointy stick spike",
	"bomb boom explosive tnt pow",
	"boob tit breast",
	"book tome",
	"boot shoe",
	"bottle jar container bowl vase vial cup",
	"brick box rectangle square cube crate",
	"break destroy broken scrambled garbled jumble smash crack",
	"bunny rabbit",
	"charge recharge re-charge battery",
	"circle curve ball round sphere disk disc loop",
	"coil hypnosis spin spiral swirl vortex",
	"consumable singleuse single-use",
	"cord rope string wire",
	"crown headwear tiara",
	"cross + religious religion sacrifice blaspheme blasphemy sacreligious",
	"dark black",
	"dead corpse death body",
	"dice reroll re-roll geek nerd",
	"drip tear drop teardrop wet liquid",
	"dupe duplicate",
	"electric zap spark lightning volt",
	"face head",
	"familiar baby follow follower child kid boy",
	"fart gas",
	"food eat",
	"fire flame burn",
	"fly flies parasite wing",
	"gamble bet",
	"garbage trash junk",
	"glow shimmer halo",
	"ghost spirit lost",
	"glasses specs shades",
	"grey gray silver",
	"grin smile",
	"gross rot puke yuck mess",
	"gold yellow",
	"guts entrails intestines organ",
	"hat cap",
	"heart <3",
	"hole opening orifice",
	"horoscope horroscope zodiac cult occult",
	"jewelry necklace locket charm bracelet",
	"knife cut sword weapon",
	"large big huge",
	"larva bug grub maggot worm",
	"light white bright",
	"map floor",
	"metal steel",
	"mom bitch",
	"money cash coin dollar $",
	"mushroom nintendo game toadstool mario koopa",
	"needle syringe inject",
	"nude naked",
	"paper page sheet",
	"chunk lump part piece shard",
	"pill capsule cylinder",
	"pink flesh",
	"photo picture",
	"poop shit crap turdy dookie pile",
	"rip torn tatter",
	"robot android drone",
	"satan devil demon evil",
	"screw nail",
	"shakey jittery",
	"shine shiny",
	"sickness sick ill",
	"song music",
	"spooky scary creepy",
	"stone rock pebble",
	"symbol shape glyph sign",
	"tech device gadget equipment",
	"testicles balls nuts scrotum",
	"teeth tooth dental",
	"text words notes write writing",
	"tool utensil",
	"vapor smoke",
	"vegetable plant fruit leaf",

	"one single 1",
	"two double 2",
	"three triple triangle 3",
	"four quad 4",
	"five 5",
	"six 6",
	"seven 7",
	"eight 8 infinity infinite",
	"nine 9",
	"ten 10",
];